### ISSUE TITLE
add collaborator

### ISSUE THREAD

**Issue by ingbrzy** [cjhyuky/MA-XML-MIUI8-Korean#10]
Please add @MarkH-UK as collaborator... thanks..

**Comment by cjhyuky** [comment]
OK. I added him ^^

**Comment by ingbrzy** [comment]
are you sure? still no write access...

**Comment by cjhyuky** [comment]
https://github.com/cjhyuky/MA-XML-MIUI8-Korean/invitations
Here's invite link
