### ISSUE TITLE
동영상 플레이어 개발자 설정에 일부 중국어 표시

### ISSUE THREAD

**Issue by noullove** [cjhyuky/MA-XML-MIUI8-Korean#11]
동영상 플레이어 앱의 설정 -> 개발자 설정 -> 버젼 선택 내부에 중문이 표시됩니다.

아마도 안정버전, 베타버전인 듯 싶네요.

그리고 "프럼 가입하기" 라는 메뉴가 있는데 "프럼" 이 아니라 "포럼" 이라고 하는게 더 맞지 않을까요?

번역 감사합니다.

**Comment by cjhyuky** [comment]
버전 선택 내부에 중문 표시가 혹시 언어를 한국어에서 영어로 바꾸고 해당메뉴에 들어가도 중국어로 나오나요?

포럼 가입하기는 오타네요. 수정하겠습니다. ^^

2016년 12월 23일 오후 3:28, noullove <notifications@github.com>님이 작성:

**Comment by zenithes** [comment]
보안 -> 전원 -> 화면 중간 배터리 '사용 시간'
'남은 시간' 또는 '사용 가능 시간' 제안드립니다. (참고로 윈도우 10은 '남은 시간'이라고 나오네요.)

감사합니다.

**Comment by zenithes** [comment]
Mi 클라우드 백업 -> 기기 백업 -> 일정 백업 '일주일일 마다 백업'
수정 부탁드립니다.

감사합니다.

**Comment by zenithes** [comment]
설정 -> 배경화면 ->슬라이드형 배경화면
'정기적으로 새로운 배경화면을 얻어 잠금 화면으로 배달합니다.'와 '모바일 데이터를 사용하여 배경화면 업데이트'가 선택 버튼과 오버랩 됩니다.
수정 부탁드립니다.

감사합니다.
