### ISSUE TITLE
잠금화면에 새로생긴 배터리 모니터가 미번역 상태입니다.

### ISSUE THREAD

**Issue by gw1021** [cjhyuky/MA-XML-MIUI8-Korean#18]
잠금화면에 새로생긴 배터리 모니터가 미번역 상태입니다.
빠른 수정해주시면 감사합니다. 노고가 많으십니다

**Comment by cjhyuky** [comment]
혹시 미번역 부분 스크린샷을 cjhyuky@gmail.com으로 보내주실 수 있으실까요?
