### ISSUE TITLE
MIUI 9

### ISSUE THREAD

**Issue by ingbrzy** [cjhyuky/MA-XML-MIUI8-Korean#19]
Can you please create a new MIUI 9 repo? 

XMLs changes repo is here
https://github.com/ingbrzy/Xiaomi.eu-MIUIv9-XML-Compare

**Comment by cjhyuky** [comment]
OKAY. I'll make it and tell you. ^^

2017. 8. 5. 오전 1:44에 "ingbrzy" <notifications@github.com>님이 작성:

**Comment by cjhyuky** [comment]
https://github.com/cjhyuky/MA-XML-MIUI9-Korean
Here's the link.
And when MIUI9 start, then I will edit the source again. ^^

2017. 8. 5. 오전 1:44에 "ingbrzy" <notifications@github.com>님이 작성:

**Comment by ingbrzy** [comment]
Thanks.. Add me and MarkH-UK as collaborator..
